- name: 'discord.js changes'
  color: '5663e9'
- name: 'gcommands changes'
  color: '5663e9'
- name: 'bug'
  color: 'f02b56'
- name: 'discussion'
  color: 'ffffff'
- name: 'has PR'
  color: '4b1f8e'
- name: 'in progress'
  color: 'ffccd7'
- name: 'question'
  color: 'd147cf'
- name: 'semver: major'
  color: 'b30e32'
- name: 'semver: minor'
  color: 'd6ad24'
- name: 'semver: patch'
  color: 'd18347'
- name: 'wontfix'
  color: 'ffffff'
- name: 'typings'
  color: '80c042'
- name: 'dependencies'
  color: '276bd1'
- name: 'packages: plugin-blacklist'
  color: 'fbca04'
- name: 'packages: plugin-cooldowns'
  color: 'fbca04'
- name: 'packages: plugin-moreevents'
  color: 'fbca04'
- name: 'packages: plugin-votes'
  color: 'fbca04'
- name: 'chore'
  color: 'ffffff'
