name: "Release"

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Package name to publish'
        required: true
        default: 'plugin-moreevents'

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Release ${{ github.event.inputs.name }}
        run: | 
          cd packages/${{ github.event.inputs.name }}
          npm ci
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}