name: 'Release'

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Package name to publish'
        required: true
        default: 'plugin-moreevents'

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Set Github Actions bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get version & asign
        id: get_version
        run: |
          cd packages/${{ github.event.inputs.name }}
          variable=$(jq --raw-output '.version' package.json)
          echo ::set-output name=version::$variable

      - name: Push changes
        run: |
          npm ci
          cd packages/${{ github.event.inputs.name }}
          npm ci
          npm run changelog

          git add --all .
          git commit -m "chore(release): ${{ steps.get_version.outputs.version }} 🎉" -m "Build ran for ${GITHUB_SHA}"
          git push -u origin master

      - name: Publish a NPM package
        run: |
          npm ci
          cd packages/${{ github.event.inputs.name }}
          npm ci
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Publish releases
        run: node ./scripts/create-release.mjs ${{ github.event.inputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
